samba-in-kubernetes/samba-centosci

- jobs/scripts/sink-clustered-deployment/sink-clustered-deployment.sh
According to the jenkins doc [1] I found the environment variable `sha1` should be set. This patch uses a shortened version to add to the tag when possible so that test runs on the same PR but different commits (pushes) done before the first test run are less likely to interfere with each other.
[1] https://plugins.jenkins.io/ghprb/
> sink: attempt to make image tag unique per push

- jobs/sink-clustered-deployment.yml
Previous commit 72240d5442626695c7f21d59784cf6166bacbf6d consumes `$sha1` inside the sink-clustered-deployment job script but it was never passed over from job definition itself.
> jobs: Update sink job to pass `$sha1`

- jobs/scripts/sink-clustered-deployment/sink-clustered-deployment.sh
- jobs/sink-clustered-deployment.yml
This fixes a problem with the previous commit where the sha1 environment variable is apparently being set to a branch name and not a sha1 (hex) hash digest value. This change skips using the sha1 as a unique id if the value doesn't appear to be a hex value.
> sink: do not use sha1 values that are not hashes

- jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
We are facing the below signature error as mentioned in the [bug #1918777](https://bugzilla.redhat.com/show_bug.cgi?id=1918777) while executing `dnf update`:
```
Running transaction check
error: /var/cache/dnf/baseos-00fe51d07def85f0/packages/NetworkManager-1.40.16-1.el8.x86_64.rpm: signature hdr data: BAD, no. of bytes(21364) out of range
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: error reading package header: '/var/cache/dnf/baseos-00fe51d07def85f0/packages/NetworkManager-1.40.16-1.el8.x86_64.rpm'
```
Due to the presence of an old pre-installed version of RPM in vagrant box for CentOS Stream 8 we were unable to perform a complete system update. Therefore make sure that we …
> jobs/scripts: Pre-fetch vagrant boxes for CentOS Stream

- deploy/Dockerfile
Installing python3-pip used to pull in already EOL'ed Python version 3.6. With more recent versions of _**jenkins-job-builde**r_ Python 3.7 is a minimum requirement due to which we started observing the following failure:
```
Traceback (most recent call last):
File "/usr/local/bin/jenkins-jobs", line 7, in <module>
from jenkins_jobs.cli.entry import main
File "/usr/local/lib/python3.6/site-packages/jenkins_jobs/cli/entry.py", line 25, in <module>
from jenkins_jobs.errors import JenkinsJobsException
File "/usr/local/lib/python3.6/site-packages/jenkins_jobs/errors.py", line 4, in <module>
from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```
**_jenkins-job-builder_** failed to check installed Python version resulting in the above run time error for which a …
> deploy/Dockerfile: Install at least Python 3.8

- jobs/sink-clustered-deployment.yml
This also removes support for testing againt v1.24.
Depends on #10
> sink: Run against Kubernetes v1.27

- jobs/scripts/gluster-integration/gluster-integration.sh
- jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
Given the fact that latest versions of vagrant libvirt boxes for CentOS Stream not getting referenced frequently we switch to generic boxes.
> jobs/scripts: Avoid pre-fetching vagrant boxes

- jobs/scripts/common/get-node.sh
With recent update to cico-workspace container image current assumption that `~/.config` existed no longer holds true. Therefore we explicitly make sure that it exists before creating `~/.config/duffy`.
Note: Fix was manually verified at jenkins instance.
> get-node.sh: Make sure that `~/.config` exists

- jobs/nightly-samba-builds.yml
> build-rpms: Replace fedora v36 builds with v38

- jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
To test installation of rpms in a container we require corresponding ansible collection and `podman` itself. In addition to that `jq` has become a requirement to parse JSON response in detecting latest Ceph development repo URLs.
> Install podman and other recent requirements

- jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
https://github.com/samba-in-kubernetes/samba-build/pull/14 is now merged.
> build-rpms: Remove all requirements for vagrant and libvirt

- deploy/jenkins.conf
As mentioned in the bug reported against python-jenkins we could specify a timeout value in order to workaround the compatibility issue with updated urllib3 dependency. More details at [launchpad #2018567](https://bugs.launchpad.net/python-jenkins/+bug/2018567).
> Use explicit timeout as workaround for python-jenkins

- jobs/scripts/gluster-integration/gluster-integration.sh
Ansible is built with Python 3.11 and thus required modules are searched from _/usr/lib/python3.11/site-packages_. Therefore force a version specific install of `netaddr` python module.
> jobs/scripts: Fix installation of `netaddr` python module

- jobs/scripts/gluster-integration/gluster-integration.sh
For every pull request on _sit-test-cases_ repository we run the entire test suite. We used to skip the scheduled nightly run of entire integration test suite for _sit-test-cases_ repository. Thus it is better to always associate entire test run with _sit-test-cases_ repository by moving the skip part to _sit-environment_ repository.
In short, [samba_gluster-integration-test-cases](https://jenkins-samba.apps.ocp.cloud.ci.centos.org/job/samba_gluster-integration-test-cases/) job from jenkins will always run the full test suite for every pull request and nightly schedule.
> jobs/scripts: Move skipping of scheduled run for sit-environment

- jobs/scripts/fs-integration/fs-integration.sh
Previously `backend` environment variable was defined conditionally for respective repositories causing it to go undefined in case of scheduled/manual runs. This resulted in running test suite always on GlusterFS, which is the default when `backend` is undefined, even for other file system backends. Therefore have it defined accordingly.
> fs-integration: Always have the `backend` variable defined in script

- jobs/scripts/fs-integration/fs-integration.sh
We explicitly install vagrant-libvirt and no longer perform internal installation using `vargant` command line.
depends on #26
> fs-integration: Remove group installation of development tools

- jobs/sink-clustered-deployment.yml
With v1.28 [released](https://github.com/kubernetes/kubernetes/releases/tag/v1.28.0) we could replace the current job for running against kubernetes v1.25 with v1.27.
> sink: Update jobs to reflect kubernetes v1.28 release

- jobs/nightly-samba-builds.yml
depends on https://github.com/samba-in-kubernetes/samba-build/pull/24
> build-rpms: Replace v4.17 jobs with v4.19

- jobs/fs-integration.yml
depends on https://github.com/samba-in-kubernetes/sit-environment/pull/17
> fs-integration: Add cephfs to the list of file systems

- jobs/scripts/fs-integration/fs-integration.sh
Nightly scheduled run against sit-environment repository used to skip the execution of testsuite. Instead we could run the basic sanity as we do for pull requests on the repository.
> fs-integration: Always run sanity test for sit-environment

- jobs/scripts/fs-integration/fs-integration.sh
We wanted to always have the statedump tarball created irrespective of the test run exit status. But the `set` bash builtin option was wrongly configured with 'x' and not 'e'. Replace '+x' with '+e' to achieve the real goal of always creating the compressed tarball of statedump directory.
See [manual](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html) for more details.
> fs-integration: Fix `set` bash builtin option

- jobs/fs-integration.yml
Hereafter require a GitHub label(`centos-ci/glusterfs`) on pull requests against [sit-test-cases](https://github.com/samba-in-kubernetes/sit-test-cases) repository to trigger full test suite run for GlusterFS.
_Please note that in addition to setting the required label corresponding keywords are to be made as GitHub comment to trigger the job. In this case a comment in the form `/test centos-ci/glusterfs` or `/retest centos-ci/glusterfs` is expected after **centos-ci/glusterfs** label is set on the pull request. This extra step can't be avoided due to an open issue https://github.com/jenkinsci/ghprb-plugin/issues/496_
> fs-integration: Avoid running full test suite always for GlusterFS

- jobs/sink-clustered-deployment.yml
Instead of triggering runs against recent 3 kubernetes version for every PR on [samba-operator](https://github.com/samba-in-kubernetes/samba-operator) repository modify job definition to only trigger the run against latest kubernetes version.
> sink: Make pull request runs limited to latest k8s version

- jobs/nightly-samba-builds.yml
> build-rpms: Replace fedora v37 builds with v39

- jobs/fs-integration.yml
- jobs/nightly-samba-builds.yml
- jobs/scripts/fs-integration/fs-integration.sh
- jobs/sink-clustered-deployment.yml
* `-x` was added in initial stages when we were keen on looking into failures during various steps of command execution. Over time it has become stable and we no longer require to list every command that is being executed in the console output. In fact this was already a TODO and can be fixed now.
* Be explicit about the shell command options so that `-x` is not included by default.
> jobs: Avoid displaying expanded commands in execution

- jobs/sink-clustered-deployment.yml
With [v1.29]( https://github.com/kubernetes/kubernetes/releases/tag/v1.29.0) released we could replace the current job for running against kubernetes v1.26 with v1.28.
> sink: Update jobs to reflect kubernetes v1.29 release

- jobs/scripts/fs-integration/fs-integration.sh
Very recently on CentOS Stream 8 ansible version got updated to _v2.16.3_ built with Python 3.12. Due to unavailability of minimum required python 3.12 modules playbook execution started to fail as follows:
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleFilterError: The ipaddr filter requires python's netaddr be installed on the ansible controller
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleFilterError: The ipaddr filter requires python's netaddr be installed on the ansible controller"}
Therefore switch python module installation from RPMs to pip.
> fs-integration: Install python modules using pip

- jobs/fs-integration.yml
- jobs/scripts/fs-integration/fs-integration.sh
Make use of the dedicated AWS S3 bucket to download the latest version of Storage Scale Developer Edition
- Configure jenkins job to fetch S3 keys
- Download and install AWS CLI
- Configure S3 keys via AWS CLI
- Download Storage Scale using the dedicated bucket
Finally add GPFS to the list of filesystems.
depends on https://github.com/samba-in-kubernetes/sit-environment/pull/24
> fs-integration: Add GPFS to the list of filesystems

- jobs/fs-integration.yml
depends on https://github.com/samba-in-kubernetes/sit-environment/pull/91
> fs-integration: Add GPFS scale variant to file systems list

- jobs/nightly-samba-builds.yml
depends on https://github.com/samba-in-kubernetes/samba-build/pull/33
> build-rpms: Replace v4.18 jobs with v4.20

- jobs/sink-clustered-deployment.yml
Kubernetes [v1.30](https://github.com/kubernetes/kubernetes/releases/tag/v1.30.0) GA.
> sink: Update jobs to reflect kubernetes v1.30 release

- jobs/nightly-samba-builds.yml
CentOS Stream 8 reached EOL on 31st May 2024.
> build-rpms: Remove CentOS 8 based builds

- jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh
With https://github.com/samba-in-kubernetes/samba-build/pull/48 we combine version specific build targets for CentOS using a general makefile rule.
depends on https://github.com/samba-in-kubernetes/samba-build/pull/48
> build-rpms: Use common target to build rpms

- jobs/fs-integration.yml
depends on https://github.com/samba-in-kubernetes/sit-environment/pull/113
> fs-integration: Add mgr module variant to ceph

- jobs/fs-integration.yml
Optimizations included:
- `cephfs.vfs` configuration is grouped inside `cephfs`.
- `cephfs.mgr.vfs` can be just `cephfs.mgr`.
depends on https://github.com/samba-in-kubernetes/sit-environment/pull/117
> fs-integraiton: Refresh the file system variants list

- jobs/nightly-samba-builds.yml
Samba [4.21.0](https://www.samba.org/samba/history/samba-4.21.0.html) GA.
> build-rpms: Replace v4.19 jobs with v4.21

- jobs/nightly-samba-containers.yml
- jobs/scripts/common/get-node.sh
- jobs/scripts/nightly-samba-containers/nightly-samba-containers.sh
depends on https://github.com/samba-in-kubernetes/samba-container/pull/183
> Add jobs to build+push samba containers

- jobs/sink-clustered-deployment.yml
Kubernetes [v1.32](https://github.com/kubernetes/kubernetes/releases/tag/v1.32.0) GA.
> sink: Update jobs to reflect kubernetes v1.32 release
